<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" media="all" href="/assets/application-mailer-dbc5154d3c4160e8fa7ef52fa740fa402760c39b5d22c8f6d64ad5999499d263.css" />
</head>
<body>
	<preview>Verify your email address on Lightform</preview>
	<div class="container">
		<img class="mx-auto mt-4 mb-3" width="42" height="42" src="https://web.dev.cloud.lightform.com/img/Logomark+Black@100px.png" />  
		
		<div class="card">
			<div class="card-body">
				<h3 class="mb-2">Hi {{firstName}},</h3>
				In order to start using your Lightform account, you need to confirm your email address.<br>
				<a class="btn btn-success mx-auto mt-3" href="{{verificationLink}}">Verify Email Address</a><br>
				
				Thanks,<br>
				The Lightform Team
			</div>
		</div>
	</div>
</body>
</html>
