/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SignalStrength } from "./components/lf-wifi-list/wifi-signal-strength.enum";
export namespace Components {
    interface AnimationTest {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface LfWifiList {
    }
    interface LfWifiListItem {
        "index"?: number;
        "networkName": string;
        "passwordProtected": boolean;
        "signalStrength": SignalStrength;
    }
}
declare global {
    interface HTMLAnimationTestElement extends Components.AnimationTest, HTMLStencilElement {
    }
    var HTMLAnimationTestElement: {
        prototype: HTMLAnimationTestElement;
        new (): HTMLAnimationTestElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLfWifiListElement extends Components.LfWifiList, HTMLStencilElement {
    }
    var HTMLLfWifiListElement: {
        prototype: HTMLLfWifiListElement;
        new (): HTMLLfWifiListElement;
    };
    interface HTMLLfWifiListItemElement extends Components.LfWifiListItem, HTMLStencilElement {
    }
    var HTMLLfWifiListItemElement: {
        prototype: HTMLLfWifiListItemElement;
        new (): HTMLLfWifiListItemElement;
    };
    interface HTMLElementTagNameMap {
        "animation-test": HTMLAnimationTestElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "lf-wifi-list": HTMLLfWifiListElement;
        "lf-wifi-list-item": HTMLLfWifiListItemElement;
    }
}
declare namespace LocalJSX {
    interface AnimationTest {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface LfWifiList {
    }
    interface LfWifiListItem {
        "index"?: number;
        "networkName": string;
        "passwordProtected": boolean;
        "signalStrength": SignalStrength;
    }
    interface IntrinsicElements {
        "animation-test": AnimationTest;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "lf-wifi-list": LfWifiList;
        "lf-wifi-list-item": LfWifiListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animation-test": LocalJSX.AnimationTest & JSXBase.HTMLAttributes<HTMLAnimationTestElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "lf-wifi-list": LocalJSX.LfWifiList & JSXBase.HTMLAttributes<HTMLLfWifiListElement>;
            "lf-wifi-list-item": LocalJSX.LfWifiListItem & JSXBase.HTMLAttributes<HTMLLfWifiListItemElement>;
        }
    }
}
